# true color
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on 

set-option -g focus-events on
set-option -sg escape-time 10

set -g pane-base-index 1
set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# set -g status-left '#[bold]#S: #{?client_prefix,★ ,}'
# set -g status-right "#[fg=magenta]RAM: #(free -h | awk '/Mem:/ {print $3 \"/\" $2}')"

bg="#2b2d2f"
accent="#a8c5a0"   # sage green

set -g window-status-current-style  "bg=#e8c99a,fg=#2b2d2f,bold"
set -g window-status-current-format " #I #W "
set -g window-status-style          "fg=#6b7280"
set -g window-status-format         " #I #W "

set -g status-style          "bg=#2b2d2f"
set -g status-left-length    30
set -g status-right-length   40

set -g status-left  '#[bg=#a8c5a0,fg=#2b2d2f,bold] #S #[bg=#2b2d2f,fg=#a8c5a0]#{?client_prefix,#[fg=#e8a598] ● ,  }'
set -g status-right '#[fg=#c4a882,bg=#2b2d2f] 󰍛 #(free -h | awk "/Mem:/ {print \$3\"/\"\$2}") '

